// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scientific_Journal_Publication_Trend_Tracking_System.Infrastructure.Persistence;

#nullable disable

namespace Scientific_Journal_Publication_Trend_Tracking_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623025230_AddFollowSubscriptionsAndStream02Sync")]
    partial class AddFollowSubscriptionsAndStream02Sync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeywordResearchTopic", b =>
                {
                    b.Property<Guid>("KeywordsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchTopicsId")
                        .HasColumnType("uuid");

                    b.HasKey("KeywordsId", "ResearchTopicsId");

                    b.HasIndex("ResearchTopicsId");

                    b.ToTable("KeywordResearchTopic");
                });

            modelBuilder.Entity("PaperAuthors", b =>
                {
                    b.Property<Guid>("AuthorsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchPapersId")
                        .HasColumnType("uuid");

                    b.HasKey("AuthorsId", "ResearchPapersId");

                    b.HasIndex("ResearchPapersId");

                    b.ToTable("PaperAuthors");
                });

            modelBuilder.Entity("PaperKeywords", b =>
                {
                    b.Property<Guid>("ResearchKeywordsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchPapersId")
                        .HasColumnType("uuid");

                    b.HasKey("ResearchKeywordsId", "ResearchPapersId");

                    b.HasIndex("ResearchPapersId");

                    b.ToTable("PaperKeywords");
                });

            modelBuilder.Entity("PaperTopics", b =>
                {
                    b.Property<Guid>("ResearchPapersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchTopicsId")
                        .HasColumnType("uuid");

                    b.HasKey("ResearchPapersId", "ResearchTopicsId");

                    b.HasIndex("ResearchTopicsId");

                    b.ToTable("PaperTopics");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ApiDataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RequestsPerMinute")
                        .HasColumnType("integer");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ApiDataSources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("654c4415-64de-48f7-a0ea-094c00491f27"),
                            BaseUrl = "https://api.openalex.org",
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastSyncTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "OpenAlex",
                            RequestsPerMinute = 100,
                            SourceType = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HomepageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Orcid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PublicationCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ResearchPaperId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResearchTopicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("ResearchPaperId");

                    b.HasIndex("ResearchTopicId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookmarks", (string)null);
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.DashboardReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveUsersCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MostCitedPapers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TopResearchDomains")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalPapersCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DashboardReports", (string)null);
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.FollowSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResearchTopicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("ResearchTopicId");

                    b.HasIndex("UserId", "IsActive");

                    b.HasIndex("UserId", "JournalId")
                        .IsUnique()
                        .HasFilter("\"JournalId\" IS NOT NULL");

                    b.HasIndex("UserId", "ResearchTopicId")
                        .IsUnique()
                        .HasFilter("\"ResearchTopicId\" IS NOT NULL");

                    b.ToTable("FollowSubscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_FollowSubscriptions_TargetMatchesType", "(\"Type\" = 0 AND \"JournalId\" IS NOT NULL AND \"ResearchTopicId\" IS NULL) OR (\"Type\" = 1 AND \"JournalId\" IS NULL AND \"ResearchTopicId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Journal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstablishedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Issn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IssueNumber")
                        .HasColumnType("text");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TotalPapersPublished")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Journals", (string)null);
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FrequencyCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Keywords", (string)null);
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RelatedJournalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedPaperId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedResearchTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RelatedJournalId");

                    b.HasIndex("RelatedPaperId");

                    b.HasIndex("RelatedResearchTopicId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RelatedPaperId")
                        .IsUnique()
                        .HasFilter("\"RelatedPaperId\" IS NOT NULL");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.PublicationTrend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageCitations")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("GrowthRate")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("KeywordId")
                        .HasColumnType("uuid");

                    b.Property<int>("PublicationCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResearchPaperId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchTopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("KeywordId");

                    b.HasIndex("ResearchPaperId");

                    b.HasIndex("ResearchTopicId");

                    b.HasIndex("Year", "ResearchTopicId");

                    b.ToTable("PublicationTrends", (string)null);
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.RefreshTokenHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokenHistories", (string)null);
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchPaper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abstract")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ApiSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CitationCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Doi")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Domain")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsFullTextAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Doi")
                        .IsUnique();

                    b.HasIndex("ExternalId");

                    b.HasIndex("JournalId");

                    b.HasIndex("PublicationYear");

                    b.HasIndex("Title");

                    b.ToTable("ResearchPapers", (string)null);
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Domain")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PapersCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ResearchTopics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0bdaedb8-f741-4cf6-87c6-b82951db7d31"),
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Research related to computing, software, algorithms, and information systems.",
                            Domain = 0,
                            Name = "Computer Science",
                            PapersCount = 0,
                            UpdatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8698ace8-d52d-48d6-b750-319684d0ea30"),
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Research related to artificial intelligence and intelligent systems.",
                            Domain = 1,
                            Name = "Artificial Intelligence",
                            PapersCount = 0,
                            UpdatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.SyncJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiDataSourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("BatchSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastRunTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextScheduledRun")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApiDataSourceId");

                    b.HasIndex("IsActive");

                    b.ToTable("SyncJobs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f95e2d4-86c3-41e2-ae16-7dba70d82747"),
                            ApiDataSourceId = new Guid("654c4415-64de-48f7-a0ea-094c00491f27"),
                            BatchSize = 100,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            CronExpression = "0 0 * * 0",
                            IsActive = true,
                            JobName = "Weekly Artificial Intelligence Paper Sync",
                            RetryAttempts = 3,
                            SearchQuery = "Artificial Intelligence",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.SyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiDataSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutionEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExecutionStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<int>("NotificationsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("integer");

                    b.Property<Guid>("SyncJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApiDataSourceId");

                    b.HasIndex("ExecutionStartTime");

                    b.HasIndex("SyncJobId");

                    b.ToTable("SyncLogs", (string)null);
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("KeywordResearchTopic", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchTopic", null)
                        .WithMany()
                        .HasForeignKey("ResearchTopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PaperAuthors", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchPaper", null)
                        .WithMany()
                        .HasForeignKey("ResearchPapersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PaperKeywords", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Keyword", null)
                        .WithMany()
                        .HasForeignKey("ResearchKeywordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchPaper", null)
                        .WithMany()
                        .HasForeignKey("ResearchPapersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PaperTopics", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchPaper", null)
                        .WithMany()
                        .HasForeignKey("ResearchPapersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchTopic", null)
                        .WithMany()
                        .HasForeignKey("ResearchTopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Journal", "Journal")
                        .WithMany("Bookmarks")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchPaper", "ResearchPaper")
                        .WithMany("Bookmarks")
                        .HasForeignKey("ResearchPaperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchTopic", "ResearchTopic")
                        .WithMany()
                        .HasForeignKey("ResearchTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");

                    b.Navigation("ResearchPaper");

                    b.Navigation("ResearchTopic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.FollowSubscription", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Journal", "Journal")
                        .WithMany("FollowSubscriptions")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchTopic", "ResearchTopic")
                        .WithMany("FollowSubscriptions")
                        .HasForeignKey("ResearchTopicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.User", "User")
                        .WithMany("FollowSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");

                    b.Navigation("ResearchTopic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Journal", "RelatedJournal")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedJournalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchPaper", "RelatedPaper")
                        .WithMany()
                        .HasForeignKey("RelatedPaperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchTopic", "RelatedResearchTopic")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedResearchTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedJournal");

                    b.Navigation("RelatedPaper");

                    b.Navigation("RelatedResearchTopic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.PublicationTrend", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Journal", "Journal")
                        .WithMany("PublicationTrends")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Keyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchPaper", null)
                        .WithMany("PublicationTrends")
                        .HasForeignKey("ResearchPaperId");

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchTopic", "ResearchTopic")
                        .WithMany("PublicationTrends")
                        .HasForeignKey("ResearchTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");

                    b.Navigation("Keyword");

                    b.Navigation("ResearchTopic");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.RefreshTokenHistory", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.User", "User")
                        .WithMany("RefreshTokenHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchPaper", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Journal", "Journal")
                        .WithMany("ResearchPapers")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.SyncJob", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ApiDataSource", "ApiDataSource")
                        .WithMany("SyncJobs")
                        .HasForeignKey("ApiDataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiDataSource");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.SyncLog", b =>
                {
                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ApiDataSource", "ApiDataSource")
                        .WithMany("SyncLogs")
                        .HasForeignKey("ApiDataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.SyncJob", "SyncJob")
                        .WithMany("SyncLogs")
                        .HasForeignKey("SyncJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiDataSource");

                    b.Navigation("SyncJob");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ApiDataSource", b =>
                {
                    b.Navigation("SyncJobs");

                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.Journal", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("FollowSubscriptions");

                    b.Navigation("Notifications");

                    b.Navigation("PublicationTrends");

                    b.Navigation("ResearchPapers");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchPaper", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("PublicationTrends");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.ResearchTopic", b =>
                {
                    b.Navigation("FollowSubscriptions");

                    b.Navigation("Notifications");

                    b.Navigation("PublicationTrends");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.SyncJob", b =>
                {
                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("Scientific_Journal_Publication_Trend_Tracking_System.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("FollowSubscriptions");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokenHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
